name: api build

on:
    push:
        tags:
          - "v*"
    workflow_dispatch:

jobs:
    update-api-doc:
        runs-on: ubuntu-latest
        environment: release
        permissions:
          contents: write
          pull-requests: write
          id-token: write
        steps:
          - uses: actions/checkout@v3
    
          - uses: pdm-project/setup-pdm@v4
            name: Setup PDM
            with:
              python-version: 3.9
              cache: true
          - name: Install dependencies
            run: pdm install
    
          - name: Remove API Doc
            run: rm -rf docs/source/pages/api

          - name: Build API Doc
            run: |
              # cd docs
              # make api build
              cp packages/iamai-adapter-apscheduler/iamai/adapter/apscheduler iamai/adapter/apscheduler
              cp packages/iamai-adapter-apscheduler/iamai/adapter/bililive iamai/adapter/bililive
              cp packages/iamai-adapter-apscheduler/iamai/adapter/console iamai/adapter/console
              cp packages/iamai-adapter-apscheduler/iamai/adapter/gensokyo iamai/adapter/gensokyo
              cp packages/iamai-adapter-apscheduler/iamai/adapter/kook iamai/adapter/kook
              cp packages/iamai-adapter-apscheduler/iamai/adapter/onebot11 iamai/adapter/onebot11
              cp packages/iamai-adapter-apscheduler/iamai/adapter/red iamai/adapter/red
              pdm run sphinx-apidoc -o docs/source/pages/api iamai packages -f -e --tocfile index
              rm -rf iamai/adapter/apscheduler
              rm -rf iamai/adapter/bililive
              rm -rf iamai/adapter/console
              rm -rf iamai/adapter/gensokyo
              rm -rf iamai/adapter/kook
              rm -rf iamai/adapter/onebot11
              rm -rf iamai/adapter/red
            shell: bash
            env:
              iamai_DEV: "1"

          - name: Commit 
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
              branch: master
              commit_message: "chore(docs): update api docs with sphinx-apidoc"
    
          # - name: Create Pull Request
          #   uses: peter-evans/create-pull-request@v5
          #   with:
          #     token: ${{ secrets.GITHUB_TOKEN }}
          #     commit-message: "chore(docs): update api docs"
          #     title: "chore(docs): update api docs"
          #     body: "automatic update api docs"
          #     branch: docs/update-api-docs
          #     base: master